# Generated by Django 5.1.3 on 2024-11-23 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('gambar', models.URLField()),
                ('mp3file', models.URLField()),
                ('keterangan', models.TextField()),
            ],
        ),
    ]
