# Generated by Django 5.1.3 on 2024-11-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_card_mp3file'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mp3file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
